#!/usr/bin/env bash

if command -v nvim >/dev/null ; then
  if [ ! -f "$HOME/.config/nvim/autoload/plug.vim" ] ; then
    echo "Setting up vim-plug for nvim"
    curl --create-dirs -fsSLo ~/.config/nvim/autoload/plug.vim \
	    https://raw.github.com/junegunn/vim-plug/master/plug.vim
  fi

  if [ ! -d "$HOME/.local/nvim/plugged" ] ; then
    echo "Installing nvim plugins"
    nvim '+PlugClean!' '+PlugInstall' '+PlugUpdate' '+qall'
  fi
fi

if [ ! -d "$HOME/.tmux/plugins/tpm" ] ; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

# vim: set ft=sh:
