#!/usr/bin/env bash

if command -v nvim >/dev/null ; then
	if [ ! -f "$HOME/.config/nvim/autoload/plug.vim" ] ; then
		echo "Setting up vim-plug for nvim"
		curl --create-dirs -fsSLo ~/.config/nvim/autoload/plug.vim \
			https://raw.github.com/junegunn/vim-plug/master/plug.vim
	fi

	if [ ! -d "$HOME/.config/nvim/plugged" ] ; then
		echo "Installing nvim plugins"
		nvim '+PlugClean!' '+PlugInstall' '+PlugUpdate' '+qall'
	fi
fi


# vim: set ft=sh :
