#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Hack:Bold:12.0"
yabai -m config status_bar_icon_font         "Font Awesome 5 Free:Solid:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip         8 9 0
yabai -m config status_bar_space_icon        🍸
yabai -m config status_bar_clock_icon        

# Update battery status bar icon
function update_battery_loop() {
	while true; do
		# Get the current battery percentage.
		battery=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)

		if [ $battery -gt 84 ]; then
			yabai -m config status_bar_power_icon_strip battery-full plug
		elif [ $battery -gt 60 ]; then
			yabai -m config status_bar_power_icon_strip battery-three-quarters plug
		elif [ $battery -gt 40 ]; then
			yabai -m config status_bar_power_icon_strip battery-half plug
		elif [ $battery -gt 14 ]; then
			yabai -m config status_bar_power_icon_strip battery-quarter plug
		else
			yabai -m config status_bar_power_icon_strip battery-empty plug
		fi

		# wait 5 minutes
		sleep $frequency
	done
}

# run the function async
update_battery_loop &

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          2
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10

# specific space settings
yabai -m config --space 7 layout             float

# some rules
yabai -m rule --add app=Slack space=1
yabai -m rule --add app=Todoist space=1
yabai -m rule --add app="^System Preferences$" manage=off border=off
yabai -m rule --add app="^Google Play Music Desktop Player" space=5
yabai -m rule --add app=Transmission space=6
yabai -m rule --add app=Steam space=7
yabai -m rule --add app="^Notes$" manage=off border=off
yabai -m rule --add app="^Logic Pro X" manage=off border=off
yabai -m rule --add app="^PCalc" manage=off border=off

echo "yabai configuration loaded.."
